# Cấu hình
server.id=1
server.log.display=false
server.port=14444
db.host=127.0.0.1
db.port=3306
db.user=root
db.password=
db.dbname=schoolzz
db.driver=com.mysql.cj.jdbc.Driver
db.minconnections=15
db.maxconnections=20
mongodb.host=localhost
mongodb.port=27017
mongodb.dbname=
mongodb.user=
mongodb.password=
websocket.host=ws://localhost
websocket.port=14444

# Tham phần trảm nâng cấp đá
game.upgrade.percent.add=0

# Giảm giá goosho
game.store.discount=0

# Shinwa
game.shinwa.active=true
game.shinwa.fee=5000

# Tăng tài đá item có thể đặt trong shinwa
game.shinwa.max=100

# Người chơi bán tài đá số lượng item cho shinwa
game.shinwa.player.max=30

# Lôi đài
game.arena.active=true

# Giới hạn ip đăng nhập
game.login.limit=50

# Số lượng item hiển thị tại
game.quantity.display.max=65535

server.notification=Hellos
game.data.version=17
game.item.version=17
game.map.version=17
game.skill.version=17
game.maxLv=131

threadPoolSize=50
scheduledPoolSize=20
game.event=Exe_Z.event.SumMer

# Set thời gian kết thúc event
event.year=2025
event.month=9
event.day=27
event.hour=23
event.minute=59
event.second=59

client.data.size.max=1024

# Tăng dame quái theo % (thấp nhất 1)
percent.damemob=2

# True Lưu SQL False Lưu Mongo
open.historySQL=false
