## C?u h?nh Database MariaDB trên Termux
server.db.ip=127.0.0.1
server.db.port=3306
server.db.name=hashirama
server.db.us=root
server.db.pw=
server.db.maxactive=100

## C?u h?nh Game Server
server.sv=1
server.port=14445
server.sv1=Nro:127.0.0.1:14445:0,0,0

server.waitlogin=5
server.maxperip=10
server.maxplayer=1000
server.expserver=1
server.debug=false
server.name=Hashirama Termux
server.domain=http://127.0.0.1:8888/

api.port=8085
api.key=abcdefJKLMNOPQR@STUVWXYrstuv@wABCDEF@GZabxyz

# C?u h?nh HikariCP t?i ýu RAM trên Android
server.hikari.minIdle=2
server.hikari.poolSize=20
server.hikari.cachePre=true
server.hikari.cacheSize=100
server.hikari.cacheSqlLimit=2048

execute.command=java -Xms256m -Xmx1024m -jar server.jar

server.event=6
server.tile.roi.a=1
server.tile.roi.b=3
